name: OCI Image

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: docker

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ forge.ref_name == 'master' }}
          context: .
          tags: ${{ vars.REGISTRY_URL }}/${{ forge.repository }}:latest
